services:
  # server:
  #   build:
  #     context: .
  #     target: final
  #   ports:
  #     - 5005:500

  # ScyllaDB
  scylla:
    image: scylladb/scylla
    container_name: name-service-scylla
    ports:
      - "9042:9042"
    command: --smp 1 --memory 750M --overprovisioned 1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESC KEYSPACES;'"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - scylla_data:/var/lib/scylla
    networks:
      - name-service-network

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: name-service-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - name-service-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: name-service-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - name-service-network

  # Kafka UI (Optional but helpful for development)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: name-service-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - name-service-network

volumes:
  scylla_data:
    driver: local

networks:
  name-service-network:
    driver: bridge